services:
  api:
    container_name: nest_api
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo_db
    restart: always
    volumes:
    - .:/www/src/node_modules
    - .:/www/src/app
    networks:
      - api_mongo
  mongo_db:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - api_mongo
networks:
  api_mongo:
    driver: bridge
volumes:
  mongo_data: